name: LSIF
on:
  - push
jobs:
  lsif-ts:
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-node
    strategy:
      matrix:
        root:
          - packages/cli
          - packages/common
          - packages/demo-app
          - packages/eslint-plugin
          - packages/toolkit-css
          - packages/toolkit-packages
          - packages/toolkit-ts
          - packages/transforms

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn --ignore-engines --ignore-scripts

      - name: Generate LSIF data
        working-directory: ${{ matrix.root }}
        run: lsif-tsc -p .

      - name: Upload lsif-tsc dump to Cloud
        working-directory: ${{ matrix.root }}
        run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
        env:
          SRC_ENDPOINT: https://sourcegraph.com/
      - name: Upload lsif-tsc dump to Dogfood
        working-directory: ${{ matrix.root }}
        run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress || true
        env:
          SRC_ENDPOINT: https://k8s.sgdev.org/
