name: LSIF
on:
  - push
jobs:
  lsif-ts:
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-node
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn --ignore-engines --ignore-scripts
      - name: Generate LSIF data
        run: lsif-tsc -p .
      - name: Upload LSIF data
        run: src lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}
