name: SCIP
on:
  - push
jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn global add @sourcegraph/scip-typescript @sourcegraph/src
      - run: yarn --ignore-engines --ignore-scripts
      - run: scip-typescript index --yarn-workspaces
      - name: Upload SCIP to Cloud
        run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
        env:
          SRC_ENDPOINT: https://sourcegraph.com/
      - name: Upload SCIP to Dogfood
        run: src lsif upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress || true
        env:
          SRC_ENDPOINT: https://k8s.sgdev.org/
